---
# 1. Create ServiceAccount in 'jenkins' namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent-sa
  namespace: jenkins
---  

# Create Role in 'backend' namespace with permissions to deploy resources
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-role
  namespace: backend
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups: [""]
  resources:
  - pods
  - services
  - configmaps
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs:
  - create
  - update
  - patch
  - delete
---
# Create RoleBinding in 'backend' binding the Role to the jenkins-agent 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-deployer-binding
  namespace: backend
subjects:
  - kind: ServiceAccount
    name: jenkins-agent-sa
    namespace: jenkins
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
---

